### ISSUE TITLE
Problem running fsleyes

### ISSUE THREAD

**Issue by JonteP** [NeuroDesk/neurodesktop#110]
Running neurodesk with `docker run --shm-size=1gb -it --privileged --name neurodesktop -v C:/neurodesktop-storage:/neurodesktop-storage -p 8080:8080 -h neurodesktop-20220813 vnmd/neurodesktop:20220813`

and loading FSL with `ml fsl/6.0.5.1`

and then running `fsleyes` gives the following error:

`user@neurodesktop-latest:~$ fsleyes
Traceback (most recent call last):
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/bin/fsleyes", line 11, in <module>
    sys.exit(main())
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/filtermain.py", line 207, in main
    result = fm.main(args)
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/main.py", line 243, in main
    fsleyes.initialise()
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/__init__.py", line 253, in initialise
    plugins.initialise()
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/plugins/__init__.py", line 225, in initialise
    _loadBuiltIns()
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/plugins/__init__.py", line 269, in _loadBuiltIns
    mod  = importlib.import_module(name)
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/fsleyes/plugins/controls/filetreepanel/__init__.py", line 18, in <module>
    import file_tree
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/file_tree/__init__.py", line 16, in <module>
    from .file_tree import FileTree, convert  # noqa: F401
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/file_tree/file_tree.py", line 14, in <module>
    import xarray
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/xarray/testing.py", line 9, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/xarray/core/duck_array_ops.py", line 26, in <module>
    from . import dask_array_compat, dask_array_ops, dtypes, npcompat, nputils
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/xarray/core/npcompat.py", line 72, in <module>
    _SupportsDType[np.dtype],
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/typing.py", line 897, in __class_getitem__
    _check_generic(cls, params)
  File "/opt/fsl-6.0.5.1/fslpython/envs/fslpython/lib/python3.8/site-packages/typing_extensions.py", line 95, in _check_generic
    raise TypeError(f"{cls} is not a generic class")
TypeError: <class 'numpy.typing._dtype_like._SupportsDType'> is not a generic class`

**Comment by stebo85** [comment]
Dear @JonteP 

Thank you for finding this bug! We will fix this with the next release.

As a workaround for now you can use the previous version of fsl:
ml fsl/6.0.4

and fsleyes will work there without any problems :)

Thank you
Steffen

**Comment by JonteP** [comment]
Thank you, Steffen, for a great project

**Comment by stebo85** [comment]
closed. Fixed and working in all releases.
